./gradlew clean :apollo-android-support:bintrayUpload
./gradlew clean :apollo-api:bintrayUpload
./gradlew clean :apollo-compiler:bintrayUpload
./gradlew clean :apollo-coroutines-support:bintrayUpload
./gradlew clean :apollo-espresso-support:bintrayUpload
./gradlew clean :apollo-gradle-plugin:bintrayUpload
./gradlew clean :apollo-http-cache:bintrayUpload
./gradlew clean :apollo-runtime:bintrayUpload
./gradlew clean :apollo-rx2-support:bintrayUpload
./gradlew clean :apollo-rx-support:bintrayUpload