{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fragments",
    "module": "fragments",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0.aar",
          "url": "fragments-1.0.0.aar",
          "size": 9640,
          "sha512": "9dac4faac4a3bae9ac9db8ffa323de4ce7708735776633efb940865f6191884363936eeab95d09660ffbf8e2476939f0c8c00ee1af4eb6e86d354eda5298e298",
          "sha256": "bf194d905047f56c453943a51957b97a35033bcb5de3ce02df97e2be1b42d400",
          "sha1": "726194f9466baf61c88adf8d8e9bbbf57a3b4e39",
          "md5": "15c6c4d65c0ff90b3a4d3dfc3682035f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0.aar",
          "url": "fragments-1.0.0.aar",
          "size": 9640,
          "sha512": "9dac4faac4a3bae9ac9db8ffa323de4ce7708735776633efb940865f6191884363936eeab95d09660ffbf8e2476939f0c8c00ee1af4eb6e86d354eda5298e298",
          "sha256": "bf194d905047f56c453943a51957b97a35033bcb5de3ce02df97e2be1b42d400",
          "sha1": "726194f9466baf61c88adf8d8e9bbbf57a3b4e39",
          "md5": "15c6c4d65c0ff90b3a4d3dfc3682035f"
        }
      ]
    },
    {
      "name": "apolloService1CodegenMetadataConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service1",
        "org.gradle.usage": "CodegenMetadata"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0-codegen-metadata-service1.json",
          "url": "fragments-1.0.0-codegen-metadata-service1.json",
          "size": 7014,
          "sha512": "bac4733704c4837ae780782dd9abb51ead46cb4c16e68383020521dbf2e42f1779c944fd0f64e8900acb142235f21fe2d476bdab8b9c1dc9bf4981e519f98472",
          "sha256": "f23a8e7c9fa20832035dc97bdc34af6ac37df311f9c7df76cd50355e37eabfda",
          "sha1": "65b984d34f689fe4ed1ce88e15ab3cbfba98b8ca",
          "md5": "10d87350bae445bf48e1e835c7c95f72"
        }
      ]
    },
    {
      "name": "apolloService1IrConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service1",
        "org.gradle.usage": "Ir"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0-ir-service1.json",
          "url": "fragments-1.0.0-ir-service1.json",
          "size": 1980,
          "sha512": "64206eb51a8873aaa33946b20b8f4a5cfe6d7b2f28569ae8a45336e2adc05f37443758bacd878d5dc607274fc1736dfa69cd8dbd39393910c1250f086480d6f7",
          "sha256": "87c18038b5fe8d17aa84caa86259b72e217842bbca916f5b9fc01a3cfe9236ee",
          "sha1": "a5f7b66520dc9e1f1605d94f3f2cffb60f1cb18f",
          "md5": "d496b9e0ae538f9c9cdaf6c07a6944b8"
        }
      ]
    },
    {
      "name": "apolloService1CodegenSchemaConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service1",
        "org.gradle.usage": "CodegenSchema"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    },
    {
      "name": "apolloService1OtherOptionsConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service1",
        "org.gradle.usage": "OtherOptions"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    },
    {
      "name": "apolloService2CodegenMetadataConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service2",
        "org.gradle.usage": "CodegenMetadata"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0-codegen-metadata-service2.json",
          "url": "fragments-1.0.0-codegen-metadata-service2.json",
          "size": 7014,
          "sha512": "4ec66eb7155a12d906f0443bc6c3f9daba2ea090dd2d283b16650b8b4e6000f6ea0f9edead271e7b3e27f0f59fe1cbf9c0bd5043c1486c0e5208a39366143208",
          "sha256": "21984f09de8fd927e2b3d2f3729cf4a0e96f9a68d5454a476dff9434ed450dcb",
          "sha1": "7b50303624051bff29ec6fedfb32de5d51c75c2a",
          "md5": "2315ecdb33a8f8f5b7196f606ece0954"
        }
      ]
    },
    {
      "name": "apolloService2IrConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service2",
        "org.gradle.usage": "Ir"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragments-1.0.0-ir-service2.json",
          "url": "fragments-1.0.0-ir-service2.json",
          "size": 1980,
          "sha512": "64206eb51a8873aaa33946b20b8f4a5cfe6d7b2f28569ae8a45336e2adc05f37443758bacd878d5dc607274fc1736dfa69cd8dbd39393910c1250f086480d6f7",
          "sha256": "87c18038b5fe8d17aa84caa86259b72e217842bbca916f5b9fc01a3cfe9236ee",
          "sha1": "a5f7b66520dc9e1f1605d94f3f2cffb60f1cb18f",
          "md5": "d496b9e0ae538f9c9cdaf6c07a6944b8"
        }
      ]
    },
    {
      "name": "apolloService2CodegenSchemaConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service2",
        "org.gradle.usage": "CodegenSchema"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    },
    {
      "name": "apolloService2OtherOptionsConsumable",
      "attributes": {
        "com.apollographql.direction": "Upstream",
        "com.apollographql.service": "service2",
        "org.gradle.usage": "OtherOptions"
      },
      "dependencies": [
        {
          "group": "com.schema",
          "module": "schema",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    }
  ]
}
