// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.fragment_used_twice.fragment

import kotlin.Any
import kotlin.String
import kotlin.Suppress

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
interface CharacterDetails {
  val __typename: String

  /**
   * The name of the character
   */
  val name: String

  /**
   * The date character was born.
   */
  val birthDate: Any

  companion object {
    val FRAGMENT_DEFINITION: String = """
        |fragment CharacterDetails on Character {
        |  __typename
        |  name
        |  birthDate
        |}
        """.trimMargin()
  }
}
