// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.fragment_used_twice.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller
import com.apollographql.apollo.api.internal.ResponseReader
import kotlin.Any
import kotlin.String
import kotlin.Suppress

/**
 * A humanoid creature from the Star Wars universe
 */
@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
interface HumanDetails : GraphqlFragment {
  val __typename: String

  /**
   * What this human calls themselves
   */
  val name: String

  /**
   * A character from the Star Wars universe
   */
  data class CharacterDetailsImpl(
    override val __typename: String = "Character",
    /**
     * The name of the character
     */
    override val name: String,
    /**
     * The date character was born.
     */
    override val birthDate: Any
  ) : DefaultImpl, CharacterDetails {
    override fun marshaller(): ResponseFieldMarshaller {
      return ResponseFieldMarshaller { writer ->
        HumanDetails_ResponseAdapter.CharacterDetailsImpl_ResponseAdapter.toResponse(writer, this)
      }
    }
  }

  /**
   * A humanoid creature from the Star Wars universe
   */
  data class OtherDefaultImpl(
    override val __typename: String = "Human",
    /**
     * What this human calls themselves
     */
    override val name: String
  ) : HumanDetails, DefaultImpl {
    override fun marshaller(): ResponseFieldMarshaller {
      return ResponseFieldMarshaller { writer ->
        HumanDetails_ResponseAdapter.OtherDefaultImpl_ResponseAdapter.toResponse(writer, this)
      }
    }
  }

  /**
   * A humanoid creature from the Star Wars universe
   */
  interface DefaultImpl : HumanDetails {
    override val __typename: String

    /**
     * What this human calls themselves
     */
    override val name: String

    fun asCharacterDetails(): CharacterDetails? = this as? CharacterDetails

    override fun marshaller(): ResponseFieldMarshaller
  }

  companion object {
    val FRAGMENT_DEFINITION: String = """
        |fragment HumanDetails on Human {
        |  __typename
        |  name
        |  ...CharacterDetails
        |}
        """.trimMargin()

    operator fun invoke(reader: ResponseReader): HumanDetails {
      return HumanDetails_ResponseAdapter.fromResponse(reader)
    }
  }
}
