// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.fragment_with_inline_fragment.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.internal.ResponseFieldMapper
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller
import com.apollographql.apollo.api.internal.ResponseReader
import com.example.fragment_with_inline_fragment.fragment.adapter.HeroDetailsImpl_ResponseAdapter
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
interface HeroDetail : GraphqlFragment {
  val __typename: String

  /**
   * The name of the character
   */
  val name: String

  /**
   * The friends of the character exposed as a connection with edges
   */
  val friendsConnection: FriendsConnection

  /**
   * A connection object for a character's friends
   */
  interface FriendsConnection {
    /**
     * The total number of friends
     */
    val totalCount: Int?

    /**
     * The edges for each of the character's friends.
     */
    val edges: List<Edge?>?

    fun marshaller(): ResponseFieldMarshaller

    /**
     * An edge object for a character's friends
     */
    interface Edge {
      /**
       * The character represented by this friendship edge
       */
      val node: Node?

      fun marshaller(): ResponseFieldMarshaller

      /**
       * A character from the Star Wars universe
       */
      interface Node {
        /**
         * The name of the character
         */
        val name: String

        fun marshaller(): ResponseFieldMarshaller
      }
    }
  }

  /**
   * An autonomous mechanical character in the Star Wars universe
   */
  interface Droid : HeroDetail, DroidDetail {
    override val __typename: String

    /**
     * The name of the character
     */
    override val name: String

    /**
     * The friends of the character exposed as a connection with edges
     */
    override val friendsConnection: FriendsConnection

    /**
     * This droid's primary function
     */
    override val primaryFunction: String?

    override fun marshaller(): ResponseFieldMarshaller

    /**
     * A connection object for a character's friends
     */
    interface FriendsConnection : HeroDetail.FriendsConnection {
      /**
       * The total number of friends
       */
      override val totalCount: Int?

      /**
       * The edges for each of the character's friends.
       */
      override val edges: List<Edge?>?

      override fun marshaller(): ResponseFieldMarshaller

      /**
       * An edge object for a character's friends
       */
      interface Edge : HeroDetail.FriendsConnection.Edge {
        /**
         * The character represented by this friendship edge
         */
        override val node: Node?

        override fun marshaller(): ResponseFieldMarshaller

        /**
         * A character from the Star Wars universe
         */
        interface Node : HeroDetail.FriendsConnection.Edge.Node {
          /**
           * The name of the character
           */
          override val name: String

          override fun marshaller(): ResponseFieldMarshaller
        }
      }
    }
  }

  interface Human : HeroDetail, HumanDetail {
    override val __typename: String

    /**
     * The name of the character
     */
    override val name: String

    /**
     * The friends of the character exposed as a connection with edges
     */
    override val friendsConnection: FriendsConnection

    override fun marshaller(): ResponseFieldMarshaller

    /**
     * A connection object for a character's friends
     */
    interface FriendsConnection : HeroDetail.FriendsConnection {
      /**
       * The total number of friends
       */
      override val totalCount: Int?

      /**
       * The edges for each of the character's friends.
       */
      override val edges: List<Edge?>?

      override fun marshaller(): ResponseFieldMarshaller

      /**
       * An edge object for a character's friends
       */
      interface Edge : HeroDetail.FriendsConnection.Edge {
        /**
         * The character represented by this friendship edge
         */
        override val node: Node?

        override fun marshaller(): ResponseFieldMarshaller

        /**
         * A character from the Star Wars universe
         */
        interface Node : HeroDetail.FriendsConnection.Edge.Node {
          /**
           * The name of the character
           */
          override val name: String

          override fun marshaller(): ResponseFieldMarshaller
        }
      }
    }
  }

  companion object {
    operator fun invoke(reader: ResponseReader): HeroDetail {
      return HeroDetailsImpl_ResponseAdapter.fromResponse(reader)
    }

    fun Mapper(): ResponseFieldMapper<HeroDetail> {
      return ResponseFieldMapper { reader ->
        HeroDetailsImpl_ResponseAdapter.fromResponse(reader)
      }
    }

    fun HeroDetail.droidDetails(): DroidDetail? = this as? DroidDetail

    fun HeroDetail.asDroid(): Droid? = this as? Droid

    fun HeroDetail.humanDetails(): HumanDetail? = this as? HumanDetail

    fun HeroDetail.asHuman(): Human? = this as? Human
  }
}
