[versions]
moshix = "0.14.1"

[libraries]
benchmark-gradle-plugin = "androidx.benchmark:benchmark-gradle-plugin:1.1.1"
moshix-ksp = { group = "dev.zacsweers.moshix", name = "moshi-ksp", version.ref = "moshix" }
benchmark-junit4 = "androidx.benchmark:benchmark-junit4:1.1.1"
androidx-test-core = "androidx.test:core:1.5.0"
