// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.unique_type_name.adapter

import com.apollographql.apollo.api.ResponseAdapterCache
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.internal.ListResponseAdapter
import com.apollographql.apollo.api.internal.NullableResponseAdapter
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.apollographql.apollo.api.internal.doubleResponseAdapter
import com.apollographql.apollo.api.internal.intResponseAdapter
import com.apollographql.apollo.api.internal.json.JsonReader
import com.apollographql.apollo.api.internal.json.JsonWriter
import com.apollographql.apollo.api.internal.stringResponseAdapter
import com.example.unique_type_name.HeroDetailQuery
import com.example.unique_type_name.type.Episode
import com.example.unique_type_name.type.Episode_ResponseAdapter
import kotlin.Array
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
class HeroDetailQuery_ResponseAdapter(
  customScalarAdapters: ResponseAdapterCache
) : ResponseAdapter<HeroDetailQuery.Data> {
  val nullableHeroDetailQueryAdapter:
      ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery?> =
      NullableResponseAdapter(HeroDetailQuery(customScalarAdapters))

  override fun fromResponse(reader: JsonReader): com.example.unique_type_name.HeroDetailQuery.Data {
    var heroDetailQuery: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery? = null
    reader.beginObject()
    while(true) {
      when (reader.selectName(RESPONSE_NAMES)) {
        0 -> heroDetailQuery = nullableHeroDetailQueryAdapter.fromResponse(reader)
        else -> break
      }
    }
    reader.endObject()
    return com.example.unique_type_name.HeroDetailQuery.Data(
      heroDetailQuery = heroDetailQuery
    )
  }

  override fun toResponse(writer: JsonWriter,
      value: com.example.unique_type_name.HeroDetailQuery.Data) {
    writer.beginObject()
    writer.name("heroDetailQuery")
    nullableHeroDetailQueryAdapter.toResponse(writer, value.heroDetailQuery)
    writer.endObject()
  }

  companion object {
    val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
      ResponseField(
        type = ResponseField.Type.Named.Object("Character"),
        fieldName = "heroDetailQuery",
        fieldSets = listOf(
          ResponseField.FieldSet("Human", HeroDetailQuery.HumanHeroDetailQuery.RESPONSE_FIELDS),
          ResponseField.FieldSet(null, HeroDetailQuery.OtherHeroDetailQuery.RESPONSE_FIELDS),
        ),
      )
    )

    val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
  }

  class HeroDetailQuery(
    customScalarAdapters: ResponseAdapterCache
  ) : ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery> {
    val HumanHeroDetailQueryAdapter: HumanHeroDetailQuery =
        com.example.unique_type_name.adapter.HeroDetailQuery_ResponseAdapter.HeroDetailQuery.HumanHeroDetailQuery(customScalarAdapters)

    val OtherHeroDetailQueryAdapter: OtherHeroDetailQuery =
        com.example.unique_type_name.adapter.HeroDetailQuery_ResponseAdapter.HeroDetailQuery.OtherHeroDetailQuery(customScalarAdapters)

    override fun fromResponse(reader: JsonReader):
        com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery {
      reader.beginObject()
      check(reader.nextName() == "__typename")
      val typename = reader.nextString()

      return when(typename) {
        "Human" -> HumanHeroDetailQueryAdapter.fromResponse(reader, typename)
        else -> OtherHeroDetailQueryAdapter.fromResponse(reader, typename)
      }
      .also { reader.endObject() }
    }

    override fun toResponse(writer: JsonWriter,
        value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery) {
      when(value) {
        is com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery -> HumanHeroDetailQueryAdapter.toResponse(writer, value)
        is com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery -> OtherHeroDetailQueryAdapter.toResponse(writer, value)
      }
    }

    class HumanHeroDetailQuery(
      customScalarAdapters: ResponseAdapterCache
    ) {
      val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

      val nullableListOfNullableFriendsAdapter:
          ResponseAdapter<List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends?>?>
          =
          NullableResponseAdapter(ListResponseAdapter(NullableResponseAdapter(Friends(customScalarAdapters))))

      val nullableFloatAdapter: ResponseAdapter<Double?> =
          NullableResponseAdapter(doubleResponseAdapter)

      fun fromResponse(reader: JsonReader, __typename: String?):
          com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery {
        var __typename: String? = __typename
        var name: String? = null
        var friends: List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends?>? = null
        var height: Double? = null
        while(true) {
          when (reader.selectName(RESPONSE_NAMES)) {
            0 -> __typename = stringAdapter.fromResponse(reader)
            1 -> name = stringAdapter.fromResponse(reader)
            2 -> friends = nullableListOfNullableFriendsAdapter.fromResponse(reader)
            3 -> height = nullableFloatAdapter.fromResponse(reader)
            else -> break
          }
        }
        return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery(
          __typename = __typename!!,
          name = name!!,
          friends = friends,
          height = height
        )
      }

      fun toResponse(writer: JsonWriter,
          value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery) {
        writer.beginObject()
        writer.name("__typename")
        stringAdapter.toResponse(writer, value.__typename)
        writer.name("name")
        stringAdapter.toResponse(writer, value.name)
        writer.name("friends")
        nullableListOfNullableFriendsAdapter.toResponse(writer, value.friends)
        writer.name("height")
        nullableFloatAdapter.toResponse(writer, value.height)
        writer.endObject()
      }

      companion object {
        val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.Typename,
          ResponseField(
            type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
            fieldName = "name",
          ),
          ResponseField(
            type = ResponseField.Type.List(ResponseField.Type.Named.Object("Character")),
            fieldName = "friends",
            fieldSets = listOf(
              ResponseField.FieldSet(null, Friends.RESPONSE_FIELDS)
            ),
          ),
          ResponseField(
            type = ResponseField.Type.Named.Other("Float"),
            fieldName = "height",
          )
        )

        val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
      }

      class Friends(
        customScalarAdapters: ResponseAdapterCache
      ) :
          ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends>
          {
        val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

        val listOfNullableEpisodeAdapter: ResponseAdapter<List<Episode?>> =
            ListResponseAdapter(NullableResponseAdapter(Episode_ResponseAdapter))

        val nullableListOfNullableFriendsAdapter:
            ResponseAdapter<List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends?>?>
            =
            NullableResponseAdapter(ListResponseAdapter(NullableResponseAdapter(Friends(customScalarAdapters))))

        override fun fromResponse(reader: JsonReader):
            com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends {
          var name: String? = null
          var appearsIn: List<Episode?>? = null
          var friends: List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends?>? = null
          reader.beginObject()
          while(true) {
            when (reader.selectName(RESPONSE_NAMES)) {
              0 -> name = stringAdapter.fromResponse(reader)
              1 -> appearsIn = listOfNullableEpisodeAdapter.fromResponse(reader)
              2 -> friends = nullableListOfNullableFriendsAdapter.fromResponse(reader)
              else -> break
            }
          }
          reader.endObject()
          return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends(
            name = name!!,
            appearsIn = appearsIn!!,
            friends = friends
          )
        }

        override fun toResponse(writer: JsonWriter,
            value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends) {
          writer.beginObject()
          writer.name("name")
          stringAdapter.toResponse(writer, value.name)
          writer.name("appearsIn")
          listOfNullableEpisodeAdapter.toResponse(writer, value.appearsIn)
          writer.name("friends")
          nullableListOfNullableFriendsAdapter.toResponse(writer, value.friends)
          writer.endObject()
        }

        companion object {
          val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
            ResponseField(
              type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
              fieldName = "name",
            ),
            ResponseField(
              type =
                  ResponseField.Type.NotNull(ResponseField.Type.List(ResponseField.Type.Named.Other("Episode"))),
              fieldName = "appearsIn",
            ),
            ResponseField(
              type = ResponseField.Type.List(ResponseField.Type.Named.Object("Character")),
              fieldName = "friends",
              fieldSets = listOf(
                ResponseField.FieldSet("Droid", Friends.CharacterFriends.RESPONSE_FIELDS),
                ResponseField.FieldSet("Human", Friends.CharacterFriends.RESPONSE_FIELDS),
                ResponseField.FieldSet(null, Friends.OtherFriends.RESPONSE_FIELDS),
              ),
            )
          )

          val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
        }

        class Friends(
          customScalarAdapters: ResponseAdapterCache
        ) :
            ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends>
            {
          val CharacterFriendsAdapter: CharacterFriends =
              com.example.unique_type_name.adapter.HeroDetailQuery_ResponseAdapter.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends(customScalarAdapters)

          val OtherFriendsAdapter: OtherFriends =
              com.example.unique_type_name.adapter.HeroDetailQuery_ResponseAdapter.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.OtherFriends(customScalarAdapters)

          override fun fromResponse(reader: JsonReader):
              com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends {
            reader.beginObject()
            check(reader.nextName() == "__typename")
            val typename = reader.nextString()

            return when(typename) {
              "Droid" -> CharacterFriendsAdapter.fromResponse(reader, typename)
              "Human" -> CharacterFriendsAdapter.fromResponse(reader, typename)
              else -> OtherFriendsAdapter.fromResponse(reader, typename)
            }
            .also { reader.endObject() }
          }

          override fun toResponse(writer: JsonWriter,
              value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends) {
            when(value) {
              is com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends -> CharacterFriendsAdapter.toResponse(writer, value)
              is com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.OtherFriends -> OtherFriendsAdapter.toResponse(writer, value)
            }
          }

          class CharacterFriends(
            customScalarAdapters: ResponseAdapterCache
          ) {
            val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

            val friendsConnectionAdapter:
                ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection>
                = FriendsConnection(customScalarAdapters)

            fun fromResponse(reader: JsonReader, __typename: String?):
                com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends {
              var __typename: String? = __typename
              var name: String? = null
              var friendsConnection: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection? = null
              while(true) {
                when (reader.selectName(RESPONSE_NAMES)) {
                  0 -> __typename = stringAdapter.fromResponse(reader)
                  1 -> name = stringAdapter.fromResponse(reader)
                  2 -> friendsConnection = friendsConnectionAdapter.fromResponse(reader)
                  else -> break
                }
              }
              return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends(
                __typename = __typename!!,
                name = name!!,
                friendsConnection = friendsConnection!!
              )
            }

            fun toResponse(writer: JsonWriter,
                value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends) {
              writer.beginObject()
              writer.name("__typename")
              stringAdapter.toResponse(writer, value.__typename)
              writer.name("name")
              stringAdapter.toResponse(writer, value.name)
              writer.name("friendsConnection")
              friendsConnectionAdapter.toResponse(writer, value.friendsConnection)
              writer.endObject()
            }

            companion object {
              val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
                ResponseField.Typename,
                ResponseField(
                  type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
                  fieldName = "name",
                ),
                ResponseField(
                  type =
                      ResponseField.Type.NotNull(ResponseField.Type.Named.Object("FriendsConnection")),
                  fieldName = "friendsConnection",
                  fieldSets = listOf(
                    ResponseField.FieldSet(null, FriendsConnection.RESPONSE_FIELDS)
                  ),
                )
              )

              val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
            }

            class FriendsConnection(
              customScalarAdapters: ResponseAdapterCache
            ) :
                ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection>
                {
              val nullableIntAdapter: ResponseAdapter<Int?> =
                  NullableResponseAdapter(intResponseAdapter)

              val nullableListOfNullableEdgesAdapter:
                  ResponseAdapter<List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges?>?>
                  =
                  NullableResponseAdapter(ListResponseAdapter(NullableResponseAdapter(Edges(customScalarAdapters))))

              override fun fromResponse(reader: JsonReader):
                  com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection {
                var totalCount: Int? = null
                var edges: List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges?>? = null
                reader.beginObject()
                while(true) {
                  when (reader.selectName(RESPONSE_NAMES)) {
                    0 -> totalCount = nullableIntAdapter.fromResponse(reader)
                    1 -> edges = nullableListOfNullableEdgesAdapter.fromResponse(reader)
                    else -> break
                  }
                }
                reader.endObject()
                return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection(
                  totalCount = totalCount,
                  edges = edges
                )
              }

              override fun toResponse(writer: JsonWriter,
                  value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection) {
                writer.beginObject()
                writer.name("totalCount")
                nullableIntAdapter.toResponse(writer, value.totalCount)
                writer.name("edges")
                nullableListOfNullableEdgesAdapter.toResponse(writer, value.edges)
                writer.endObject()
              }

              companion object {
                val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
                  ResponseField(
                    type = ResponseField.Type.Named.Other("Int"),
                    fieldName = "totalCount",
                  ),
                  ResponseField(
                    type = ResponseField.Type.List(ResponseField.Type.Named.Object("FriendsEdge")),
                    fieldName = "edges",
                    fieldSets = listOf(
                      ResponseField.FieldSet(null, Edges.RESPONSE_FIELDS)
                    ),
                  )
                )

                val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
              }

              class Edges(
                customScalarAdapters: ResponseAdapterCache
              ) :
                  ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges>
                  {
                val nullableNodeAdapter:
                    ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node?>
                    = NullableResponseAdapter(Node(customScalarAdapters))

                override fun fromResponse(reader: JsonReader):
                    com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges {
                  var node: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node? = null
                  reader.beginObject()
                  while(true) {
                    when (reader.selectName(RESPONSE_NAMES)) {
                      0 -> node = nullableNodeAdapter.fromResponse(reader)
                      else -> break
                    }
                  }
                  reader.endObject()
                  return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges(
                    node = node
                  )
                }

                override fun toResponse(writer: JsonWriter,
                    value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges) {
                  writer.beginObject()
                  writer.name("node")
                  nullableNodeAdapter.toResponse(writer, value.node)
                  writer.endObject()
                }

                companion object {
                  val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
                    ResponseField(
                      type = ResponseField.Type.Named.Object("Character"),
                      fieldName = "node",
                      fieldSets = listOf(
                        ResponseField.FieldSet(null, Node.RESPONSE_FIELDS)
                      ),
                    )
                  )

                  val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
                }

                class Node(
                  customScalarAdapters: ResponseAdapterCache
                ) :
                    ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node>
                    {
                  val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

                  override fun fromResponse(reader: JsonReader):
                      com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node {
                    var name: String? = null
                    reader.beginObject()
                    while(true) {
                      when (reader.selectName(RESPONSE_NAMES)) {
                        0 -> name = stringAdapter.fromResponse(reader)
                        else -> break
                      }
                    }
                    reader.endObject()
                    return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node(
                      name = name!!
                    )
                  }

                  override fun toResponse(writer: JsonWriter,
                      value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.CharacterFriends.FriendsConnection.Edges.Node) {
                    writer.beginObject()
                    writer.name("name")
                    stringAdapter.toResponse(writer, value.name)
                    writer.endObject()
                  }

                  companion object {
                    val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
                      ResponseField(
                        type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
                        fieldName = "name",
                      )
                    )

                    val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
                  }
                }
              }
            }
          }

          class OtherFriends(
            customScalarAdapters: ResponseAdapterCache
          ) {
            val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

            fun fromResponse(reader: JsonReader, __typename: String?):
                com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.OtherFriends {
              var __typename: String? = __typename
              while(true) {
                when (reader.selectName(RESPONSE_NAMES)) {
                  0 -> __typename = stringAdapter.fromResponse(reader)
                  else -> break
                }
              }
              return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.OtherFriends(
                __typename = __typename!!
              )
            }

            fun toResponse(writer: JsonWriter,
                value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.HumanHeroDetailQuery.Friends.Friends.OtherFriends) {
              writer.beginObject()
              writer.name("__typename")
              stringAdapter.toResponse(writer, value.__typename)
              writer.endObject()
            }

            companion object {
              val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
                ResponseField.Typename
              )

              val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
            }
          }
        }
      }
    }

    class OtherHeroDetailQuery(
      customScalarAdapters: ResponseAdapterCache
    ) {
      val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

      val nullableListOfNullableFriendsAdapter:
          ResponseAdapter<List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends?>?>
          =
          NullableResponseAdapter(ListResponseAdapter(NullableResponseAdapter(Friends(customScalarAdapters))))

      fun fromResponse(reader: JsonReader, __typename: String?):
          com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery {
        var __typename: String? = __typename
        var name: String? = null
        var friends: List<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends?>? = null
        while(true) {
          when (reader.selectName(RESPONSE_NAMES)) {
            0 -> __typename = stringAdapter.fromResponse(reader)
            1 -> name = stringAdapter.fromResponse(reader)
            2 -> friends = nullableListOfNullableFriendsAdapter.fromResponse(reader)
            else -> break
          }
        }
        return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery(
          __typename = __typename!!,
          name = name!!,
          friends = friends
        )
      }

      fun toResponse(writer: JsonWriter,
          value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery) {
        writer.beginObject()
        writer.name("__typename")
        stringAdapter.toResponse(writer, value.__typename)
        writer.name("name")
        stringAdapter.toResponse(writer, value.name)
        writer.name("friends")
        nullableListOfNullableFriendsAdapter.toResponse(writer, value.friends)
        writer.endObject()
      }

      companion object {
        val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.Typename,
          ResponseField(
            type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
            fieldName = "name",
          ),
          ResponseField(
            type = ResponseField.Type.List(ResponseField.Type.Named.Object("Character")),
            fieldName = "friends",
            fieldSets = listOf(
              ResponseField.FieldSet(null, Friends.RESPONSE_FIELDS)
            ),
          )
        )

        val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
      }

      class Friends(
        customScalarAdapters: ResponseAdapterCache
      ) :
          ResponseAdapter<com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends>
          {
        val stringAdapter: ResponseAdapter<String> = stringResponseAdapter

        override fun fromResponse(reader: JsonReader):
            com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends {
          var name: String? = null
          reader.beginObject()
          while(true) {
            when (reader.selectName(RESPONSE_NAMES)) {
              0 -> name = stringAdapter.fromResponse(reader)
              else -> break
            }
          }
          reader.endObject()
          return com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends(
            name = name!!
          )
        }

        override fun toResponse(writer: JsonWriter,
            value: com.example.unique_type_name.HeroDetailQuery.Data.HeroDetailQuery.OtherHeroDetailQuery.Friends) {
          writer.beginObject()
          writer.name("name")
          stringAdapter.toResponse(writer, value.name)
          writer.endObject()
        }

        companion object {
          val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
            ResponseField(
              type = ResponseField.Type.NotNull(ResponseField.Type.Named.Other("String")),
              fieldName = "name",
            )
          )

          val RESPONSE_NAMES: List<String> = RESPONSE_FIELDS.map { it.responseName }
        }
      }
    }
  }
}
