// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.named_fragment_delegate.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller
import kotlin.String
import kotlin.collections.List

/**
 * An autonomous mechanical character in the Star Wars universe
 */
data class DroidDetailsImpl(
  override val __typename: String = "Droid",
  /**
   * What others call this droid
   */
  override val name: String,
  /**
   * This droid's primary function
   */
  override val primaryFunction: String?,
  /**
   * This droid's friends, or an empty list if they have none
   */
  override val friends: List<Friend?>?
) : DroidDetail, GraphqlFragment {
  override fun marshaller(): ResponseFieldMarshaller {
    return ResponseFieldMarshaller { writer ->
      DroidDetailsImpl_ResponseAdapter.toResponse(writer, this)
    }
  }

  /**
   * A character from the Star Wars universe
   */
  data class Friend(
    /**
     * The name of the character
     */
    override val name: String
  ) : DroidDetail.Friend {
    override fun marshaller(): ResponseFieldMarshaller {
      return ResponseFieldMarshaller { writer ->
        DroidDetailsImpl_ResponseAdapter.Friend.toResponse(writer, this)
      }
    }
  }

  companion object {
    val FRAGMENT_DEFINITION: String = """
        |fragment DroidDetails on Droid {
        |  __typename
        |  name
        |  primaryFunction
        |  friends {
        |    name
        |  }
        |}
        """.trimMargin()
  }
}
