// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.fragment_in_fragment.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.internal.ResponseFieldMapper
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller
import com.apollographql.apollo.api.internal.ResponseReader
import com.example.fragment_in_fragment.fragment.adapter.PilotFragmentImpl_ResponseAdapter
import kotlin.String
import kotlin.Suppress

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
interface PilotFragment : GraphqlFragment {
  val __typename: String

  /**
   * The name of this person.
   */
  val name: String?

  /**
   * A planet that this person was born on or inhabits.
   */
  val homeworld: Homeworld?

  /**
   * A large mass, planet or planetoid in the Star Wars Universe, at the time of
   * 0 ABY.
   */
  interface Homeworld {
    val __typename: String

    fun marshaller(): ResponseFieldMarshaller

    interface Planet : Homeworld, PlanetFragment {
      override val __typename: String

      /**
       * The name of this planet.
       */
      override val name: String?

      override fun marshaller(): ResponseFieldMarshaller
    }

    companion object {
      fun Homeworld.planetFragment(): PlanetFragment? = this as? PlanetFragment

      fun Homeworld.asPlanet(): Planet? = this as? Planet
    }
  }

  companion object {
    operator fun invoke(reader: ResponseReader): PilotFragment {
      return PilotFragmentImpl_ResponseAdapter.fromResponse(reader)
    }

    fun Mapper(): ResponseFieldMapper<PilotFragment> {
      return ResponseFieldMapper { reader ->
        PilotFragmentImpl_ResponseAdapter.fromResponse(reader)
      }
    }
  }
}
