// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.simple_fragment.fragment

import com.apollographql.apollo.api.Fragment
import com.apollographql.apollo.api.Operation
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.example.simple_fragment.fragment.adapter.HeroDetailsImpl_ResponseAdapter

/**
 * Fragment with Java / Kotlin docs generation
 * with multi lines support
 */
internal class HeroDetailFragment : Fragment<HeroDetailsImpl> {
  override fun adapter(): ResponseAdapter<HeroDetailsImpl> {
    return HeroDetailsImpl_ResponseAdapter
  }

  override fun variables(): Operation.Variables = Operation.EMPTY_VARIABLES
}
