// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.arguments_simple.fragment

import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.apollographql.apollo.api.internal.ResponseReader
import com.apollographql.apollo.api.internal.ResponseWriter
import kotlin.Array
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
object HeroDetails_ResponseAdapter : ResponseAdapter<HeroDetails.HeroDetailsImpl> {
  private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
    ResponseField.forString("__typename", "__typename", null, false, null),
    ResponseField.forObject("friendsConnection", "friendsConnection", mapOf<String, Any>(
      "first" to mapOf<String, Any>(
        "kind" to "Variable",
        "variableName" to "friendsCount")), false, null)
  )

  override fun fromResponse(reader: ResponseReader, __typename: String?):
      HeroDetails.HeroDetailsImpl {
    return reader.run {
      var __typename: String? = __typename
      var friendsConnection: HeroDetails.FriendsConnection1? = null
      while(true) {
        when (selectField(RESPONSE_FIELDS)) {
          0 -> __typename = readString(RESPONSE_FIELDS[0])
          1 -> friendsConnection = readObject<HeroDetails.FriendsConnection1>(RESPONSE_FIELDS[1]) { reader ->
            FriendsConnection1_ResponseAdapter.fromResponse(reader)
          }
          else -> break
        }
      }
      HeroDetails.HeroDetailsImpl(
        __typename = __typename!!,
        friendsConnection = friendsConnection!!
      )
    }
  }

  override fun toResponse(writer: ResponseWriter, value: HeroDetails.HeroDetailsImpl) {
    writer.writeString(RESPONSE_FIELDS[0], value.__typename)
    writer.writeObject(RESPONSE_FIELDS[1]) { writer ->
      FriendsConnection1_ResponseAdapter.toResponse(writer, value.friendsConnection)
    }
  }

  object Node1_ResponseAdapter : ResponseAdapter<HeroDetails.Node1> {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
      ResponseField.forString("name", "name", null, true, listOf(
        ResponseField.Condition.booleanCondition("IncludeName", false)
      ))
    )

    override fun fromResponse(reader: ResponseReader, __typename: String?): HeroDetails.Node1 {
      return reader.run {
        var name: String? = null
        while(true) {
          when (selectField(RESPONSE_FIELDS)) {
            0 -> name = readString(RESPONSE_FIELDS[0])
            else -> break
          }
        }
        HeroDetails.Node1(
          name = name
        )
      }
    }

    override fun toResponse(writer: ResponseWriter, value: HeroDetails.Node1) {
      writer.writeString(RESPONSE_FIELDS[0], value.name)
    }
  }

  object Edge1_ResponseAdapter : ResponseAdapter<HeroDetails.Edge1> {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
      ResponseField.forObject("node", "node", null, true, null)
    )

    override fun fromResponse(reader: ResponseReader, __typename: String?): HeroDetails.Edge1 {
      return reader.run {
        var node: HeroDetails.Node1? = null
        while(true) {
          when (selectField(RESPONSE_FIELDS)) {
            0 -> node = readObject<HeroDetails.Node1>(RESPONSE_FIELDS[0]) { reader ->
              Node1_ResponseAdapter.fromResponse(reader)
            }
            else -> break
          }
        }
        HeroDetails.Edge1(
          node = node
        )
      }
    }

    override fun toResponse(writer: ResponseWriter, value: HeroDetails.Edge1) {
      if(value.node == null) {
        writer.writeObject(RESPONSE_FIELDS[0], null)
      } else {
        writer.writeObject(RESPONSE_FIELDS[0]) { writer ->
          Node1_ResponseAdapter.toResponse(writer, value.node)
        }
      }
    }
  }

  object FriendsConnection1_ResponseAdapter : ResponseAdapter<HeroDetails.FriendsConnection1> {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
      ResponseField.forInt("totalCount", "totalCount", null, true, null),
      ResponseField.forList("edges", "edges", null, true, null)
    )

    override fun fromResponse(reader: ResponseReader, __typename: String?):
        HeroDetails.FriendsConnection1 {
      return reader.run {
        var totalCount: Int? = null
        var edges: List<HeroDetails.Edge1?>? = null
        while(true) {
          when (selectField(RESPONSE_FIELDS)) {
            0 -> totalCount = readInt(RESPONSE_FIELDS[0])
            1 -> edges = readList<HeroDetails.Edge1>(RESPONSE_FIELDS[1]) { reader ->
              reader.readObject<HeroDetails.Edge1> { reader ->
                Edge1_ResponseAdapter.fromResponse(reader)
              }
            }
            else -> break
          }
        }
        HeroDetails.FriendsConnection1(
          totalCount = totalCount,
          edges = edges
        )
      }
    }

    override fun toResponse(writer: ResponseWriter, value: HeroDetails.FriendsConnection1) {
      writer.writeInt(RESPONSE_FIELDS[0], value.totalCount)
      writer.writeList(RESPONSE_FIELDS[1], value.edges) { values, listItemWriter ->
        values?.forEach { value ->
          if(value == null) {
            listItemWriter.writeObject(null)
          } else {
            listItemWriter.writeObject { writer ->
              Edge1_ResponseAdapter.toResponse(writer, value)
            }
          }
        }
      }
    }
  }
}
