name: build-pull-request

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

# Cancel any current or previous job from the same PR
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests-no-gradle:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew build -x :apollo-gradle-plugin:test

  tests-gradle:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew :apollo-gradle-plugin:test

  tests-integration:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew -p tests build 

  swift-tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - run: |
          /Applications/Xcode_26.app/Contents/Developer/usr/bin/xcodebuild -allowProvisioningUpdates -project swift-tests/swift-tests.xcodeproj -configuration Debug -scheme swift-tests  test -test-timeouts-enabled YES
