on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

# Cancel any current or previous job from the same PR
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests-gradle:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew ciTestsGradle

  tests-no-gradle:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew ciTestsNoGradle --stacktrace

  tests-integration:
    if: "!startsWith(github.head_ref, 'release-')"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew -p tests build 
          ./gradlew -p tests checkGitStatus

  ios-tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - run: |
          ./gradlew :shared-framework:assembleDebugAppleFrameworkForXcodeIosSimulatorArm64
          /Applications/Xcode_26.app/Contents/Developer/usr/bin/xcodebuild -allowProvisioningUpdates -project tests/com.apollographql.iostest/com.apollographql.iostest.xcodeproj -configuration Debug -scheme com.apollographql.iostest -sdk iphoneos test -destination name='iPhone 17 Pro' -test-timeouts-enabled YES
