name: Bump kotlin nightlies

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  push-kotlin-nightlies-branch:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Bump Kotlin version
        run: ./scripts/bump-kotlin-nightlies.main.kts
      - name: Push changes to kotlin-nightlies branch
        run: |
          git checkout -b kotlin-nightlies
          git add .
          git commit -m "Bump Kotlin version"
          git push --force origin kotlin-nightlies
