name: defer-router-tests

on:
  schedule:
    - cron: '0 3 * * *'
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  defer-with-router-tests:
    runs-on: ubuntu-latest
    if: github.repository == 'apollographql/apollo-kotlin'
    steps:
      - name: Checkout project
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install and run subgraph
        working-directory: tests/defer/router/subgraphs/computers
        run: |
          npm install
          APOLLO_PORT=4001 npm start &

      - name: Install router
        run: |
          curl -sSL https://router.apollo.dev/download/nix/latest | sh

      - name: Run router
        run: |
          ./router --supergraph tests/defer/router/simple-supergraph.graphqls &

      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2

      - name: Run Apollo Kotlin @defer tests
        env:
          DEFER_WITH_ROUTER_TESTS: true
        run: |
          ./gradlew --no-daemon --console plain -p tests :defer:allTests
