name: Kotlin 1.7

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-kotlin-1-7:
    runs-on: macos-11
    if: github.repository == 'apollographql/apollo-kotlin'
    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28 #v3
      - uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 #v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee #v2.1.4
      - name: Build with Gradle
        run: |
          ulimit -c unlimited
          # Workaround an issue where kotlinNpmInstall outputs
          # 'Resolving NPM dependencies using yarn' returns 137
          ./gradlew compileKotlinJsIr compileKotlinJsLegacy
          ./gradlew --stop
          ./gradlew ciBuild
          ./gradlew --stop
          ./gradlew -p tests ciBuild
          ./gradlew dokkaHtmlMultiModule
        env:
          COM_APOLLOGRAPHQL_VERSION_KOTLIN_PLUGIN: '1.7.10'
          COM_APOLLOGRAPHQL_VERSION_KSP_GRADLE_PLUGIN: '1.7.10-1.0.6'
          COM_APOLLOGRAPHQL_VERSION_KOTLINXDATETIME: '0.4.0'
      - name: Collect Diagnostics
        if: always()
        run: ./scripts/collect-diagnostics.main.kts
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 #v3
        if: always()
        with:
          name: build-kotlin-1-7.zip
          path: diagnostics.zip
