name: Publish IntelliJ plugin
on: workflow_dispatch

jobs:

  # Prepare and publish the plugin to the Marketplace repository
  release:
    name: Publish IntelliJ plugin
    runs-on: ubuntu-latest
    steps:

      # Check out current repository, main branch
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: main

      # Setup Java 11 environment for the next step
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.IJ_PLUGIN_PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.IJ_PLUGIN_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.IJ_PLUGIN_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.IJ_PLUGIN_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew :intellij-plugin:publishPlugin
