name: publish-snapshot-and-kdoc

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: macos-15
    if: github.event.repository.fork == false
    # Required for the `deploy-pages` action
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: |
          ./gradlew :apollo-kdoc:dokkaGeneratePublicationHtml
          ./gradlew nmcpPublishAggregationToCentralPortalSnapshots
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa #v3.0.1
        with:
          path: "libraries/apollo-kdoc/build/dokka/html"
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4.0.5