name: tests-no-gradle

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test-no-gradle:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          ulimit -c unlimited
          ./gradlew ciTestsNoGradle
      - name: Collect Diagnostics
        if: always()
        run: ./scripts/collect-diagnostics.main.kts
      - uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: tests-no-gradle.zip
          path: tests-no-gradle.zip
